# Generated by Django 4.0.4 on 2022-05-04 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Called and research in progress', 'Called and research in progress'), ('Called and customer declined services', 'Called and customer declined services'), ("Customer didn't respond", "Customer didn't respond"), ('Quote sent', 'Quote sent'), ('Event finalized', 'Event finalized'), ('Advance received', 'Advance received'), ('Event completed', 'Event completed'), ('Invoice paid in full', 'Invoice paid in full'), ('Closed', 'Closed')], default='New', max_length=100),
        ),
        migrations.CreateModel(
            name='AssignLead',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('leadID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lead')),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('app.basemodel',),
        ),
    ]
