# Generated by Django 4.0.4 on 2022-05-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_lead_status_assignlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignlead',
            name='userID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Called and research in progress', 'Called and research in progress'), ('Called and customer declined services', 'Called and customer declined services'), ("Customer didn't respond", "Customer didn't respond"), ('Quote sent', 'Quote sent'), ('Event finalized', 'Event finalized'), ('Advance received', 'Advance received'), ('Event completed', 'Event completed'), ('Invoice paid in full', 'Invoice paid in full'), ('Closed', 'Closed')], default='New', max_length=255),
        ),
    ]
