# Generated by Django 4.0.4 on 2022-05-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_assignlead_userid_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignlead',
            name='leadID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
