# Generated by Django 4.0.4 on 2022-05-07 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignlead',
            old_name='userID',
            new_name='vendorID',
        ),
        migrations.AddField(
            model_name='assignlead',
            name='last_status_updated_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='assignlead',
            name='lead_status',
            field=models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT'), ('UNASSIGN', 'UNASSIGN')], default='UNASSIGN', max_length=10),
        ),
    ]
