# Generated by Django 4.0.4 on 2022-05-07 18:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_userid_assignlead_vendorid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead_Assign',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('vendorID', models.IntegerField(blank=True, null=True)),
                ('leadID', models.IntegerField(blank=True, null=True)),
                ('lead_status', models.CharField(default='UNASSIGN', max_length=150)),
                ('last_status_updated_time', models.DateTimeField(default=datetime.datetime.now)),
                ('last_comments', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Lead_Comment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('leadID', models.IntegerField(blank=True, null=True)),
                ('leadAssignedId', models.IntegerField(blank=True, null=True)),
                ('vendorID', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='UNASSIGN', max_length=150)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            bases=('app.basemodel',),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='vendor_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='AssignLead',
        ),
    ]
