# Generated by Django 4.0.4 on 2022-05-08 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_lead_assign_lead_comment_remove_lead_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_assign',
            name='leadID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lead'),
        ),
        migrations.AlterField(
            model_name='lead_assign',
            name='vendorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead_comment',
            name='leadAssignedId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lead_assign'),
        ),
        migrations.AlterField(
            model_name='lead_comment',
            name='leadID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lead'),
        ),
        migrations.AlterField(
            model_name='lead_comment',
            name='vendorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
