# Generated by Django 4.0.4 on 2022-05-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_lead_assign_leadid_alter_lead_assign_vendorid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookup',
            name='type',
            field=models.CharField(blank=True, choices=[('category', 'category'), ('catering', 'catering'), ('max_capacity', 'max_capacity'), ('number_of_events', 'number_of_events'), ('lead_status', 'Lead Status')], max_length=100, null=True),
        ),
    ]
