# Generated by Django 4.0.4 on 2022-05-08 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_lookup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_assign',
            name='lead_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lookup'),
        ),
        migrations.AlterField(
            model_name='lead_comment',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lookup'),
        ),
    ]
