# Generated by Django 4.0.4 on 2022-05-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_lead_assign_lead_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='type',
            field=models.CharField(blank=True, choices=[('category', 'Category'), ('catering', 'Catering'), ('max_capacity', 'Max Capacity'), ('number_of_events', 'Number of Events'), ('lead_status', 'Lead Status')], max_length=100, null=True),
        ),
    ]
