# Generated by Django 4.0.4 on 2022-05-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_is_token_alter_lookup_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Verification_Token',
        ),
        migrations.RenameField(
            model_name='verification_token',
            old_name='forgot_password_token',
            new_name='token',
        ),
    ]
