# Generated by Django 4.0.4 on 2022-05-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_profile_verification_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_token',
            new_name='is_verify',
        ),
    ]
