# Generated by Django 4.0.4 on 2022-05-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_is_token_user_is_verify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification_token',
            old_name='email',
            new_name='vendorID',
        ),
    ]
