# Generated by Django 4.0.4 on 2022-05-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_email_verification_token_vendorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='date_of_event',
            field=models.DateField(blank=True, null=True, verbose_name=['%d-%m-%Y']),
        ),
        migrations.AddField(
            model_name='lead',
            name='time_of_event',
            field=models.TimeField(blank=True, null=True, verbose_name=['%I:%M %p']),
        ),
    ]
