# Generated by Django 3.2.9 on 2022-05-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20220518_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_confirmed',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
