# Generated by Django 3.2.9 on 2022-05-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_user_terms_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='terms_confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
