# DON"T REMOVE {}  FROM STRINGS< IT"S USED AS VARIBLE FOR STRING FORMATTING.
# MEDIA STORE
MEDIA_PATH_LOCATION="/vendors/{}/"
MEDIA_PATH_LOCATION_DELETE="/vendors/{}/{}/"
MEDIA_PATH_USER_LOCATION="/vendors/{}/"

# SMS SENT
SMS_SENT_TO_MESSAGE='{}/{}/{}/{}/{}'

# DATA TABLES - DON"T BE CHNAGES
START=0
PAGE_SIZE=10
ADMIN = "ADMIN"
VENDOR = "VENDOR"
